"""
Modular data layer.

The rest of the application only talks to this module. Two sources ship:

  DemoSource  — synthetic, generated from a known process (always available).
  RealDataSource — county-year panel built from U.S. Census ACS + OpenStreetMap
                   + a pilot NCAA roster scrape (available once
                   data/real/real_dataset.csv has been built; see realdata/).

Select with the env var  SPORTS_LAB_SOURCE = demo | real   (default: real if the
real dataset exists, else demo). Each source declares its own predictor and
outcome catalogue, so the modeling code and API never change.

Required schema (one row per community-year):
    community_id, community_name, state, year (int),
    population (int > 0), <predictor columns...>, <outcome columns...>
"""
from __future__ import annotations
import json
import os
from dataclasses import dataclass, asdict
from functools import lru_cache

import pandas as pd

DATA_DIR = os.path.join(os.path.dirname(__file__), "data")
DEMO_CSV = os.path.join(DATA_DIR, "demo_dataset.csv")
REAL_CSV = os.path.join(DATA_DIR, "real", "real_dataset.csv")
REAL_PROV = os.path.join(DATA_DIR, "real", "real_dataset_provenance.json")


@dataclass
class VariableSpec:
    key: str
    label: str
    description: str
    unit: str = ""


_SOCIO = [
    VariableSpec("median_income", "Median household income", "ACS median household income.", "USD"),
    VariableSpec("poverty_rate", "Poverty rate", "Share of population below the poverty line.", "%"),
    VariableSpec("pct_bachelors", "Education (bachelor's+)", "Share of adults 25+ with a bachelor's degree or higher.", "%"),
    VariableSpec("tennis_courts_per_100k", "Tennis access", "Tennis facilities (OSM) per 100k residents.", "courts/100k"),
    VariableSpec("pop_density", "Population density", "Residents per square mile.", "/sq mi"),
    VariableSpec("population", "Population", "Community population (also usable as a raw predictor).", "people"),
]
_NOISE = [
    VariableSpec(f"noise_{k}", f"Nuisance variable {k}", "Pure noise — included to demonstrate overfitting.", "")
    for k in range(1, 7)
]
_OUTCOMES = [
    VariableSpec("d1_players", "NCAA D1 tennis players (count)",
                 "How many NCAA Division I tennis players list a hometown in this community — "
                 "counted from scraped team rosters.", "players"),
    VariableSpec("d1_rate_per_100k", "NCAA D1 representation rate",
                 "NCAA D1 tennis players per 100,000 residents.", "players/100k"),
]


class DemoSource:
    key = "demo"
    name = "DEMO DATASET (synthetic)"
    is_real = False
    citation = ("Synthetic data generated by backend/generate_demo_data.py from a known "
                "negative-binomial process. NOT real NCAA or U.S. Census data.")
    notes = ("Six noise_* nuisance predictors are included so overfitting is observable.")

    def predictors(self): return _SOCIO + _NOISE
    def outcomes(self): return _OUTCOMES

    def load(self) -> pd.DataFrame:
        if not os.path.exists(DEMO_CSV):
            from generate_demo_data import build
            os.makedirs(DATA_DIR, exist_ok=True)
            build().to_csv(DEMO_CSV, index=False)
        return pd.read_csv(DEMO_CSV)


class RealDataSource:
    key = "real"
    name = "RESEARCH DATA (NCAA D1 tennis rosters + U.S. Census ACS + OpenStreetMap)"
    is_real = True

    def __init__(self):
        self._prov = {}
        if os.path.exists(REAL_PROV):
            try:
                self._prov = json.load(open(REAL_PROV))
            except Exception:
                self._prov = {}

    @property
    def citation(self) -> str:
        s = self._prov.get("sources", {})
        return " | ".join(f"{k}: {v}" for k, v in s.items()) or (
            "U.S. Census ACS 5-year; OpenStreetMap (ODbL); pilot ACC+Big Ten roster scrape.")

    @property
    def notes(self) -> str:
        lim = self._prov.get("limitations", [])
        return " ".join(lim)

    def predictors(self): return _SOCIO
    def outcomes(self): return _OUTCOMES

    def load(self) -> pd.DataFrame:
        if not os.path.exists(REAL_CSV):
            raise FileNotFoundError(
                "real_dataset.csv not found. Build it with:  "
                "cd backend && ./venv/bin/python -m realdata.pipeline  (no API key needed)."
            )
        return pd.read_csv(REAL_CSV, dtype={"community_id": str})


def _select_source():
    choice = os.environ.get("SPORTS_LAB_SOURCE", "").strip().lower()
    if choice == "demo":
        return DemoSource()
    if choice == "real":
        return RealDataSource()
    return RealDataSource() if os.path.exists(REAL_CSV) else DemoSource()


ACTIVE_SOURCE = _select_source()


@lru_cache(maxsize=1)
def get_dataframe() -> pd.DataFrame:
    return ACTIVE_SOURCE.load()


def predictors() -> list[VariableSpec]:
    return ACTIVE_SOURCE.predictors()


def outcomes() -> list[VariableSpec]:
    return ACTIVE_SOURCE.outcomes()


def available_years() -> list[int]:
    return sorted(int(y) for y in get_dataframe()["year"].unique())


def source_info() -> dict:
    df = get_dataframe()
    info = {
        "key": ACTIVE_SOURCE.key,
        "name": ACTIVE_SOURCE.name,
        "is_real": ACTIVE_SOURCE.is_real,
        "citation": ACTIVE_SOURCE.citation,
        "notes": getattr(ACTIVE_SOURCE, "notes", ""),
        "n_rows": int(len(df)),
        "n_communities": int(df["community_id"].nunique()),
        "years": available_years(),
        "geography": "U.S. county" if ACTIVE_SOURCE.is_real else "synthetic community",
    }
    if ACTIVE_SOURCE.is_real and getattr(ACTIVE_SOURCE, "_prov", None):
        info["provenance"] = ACTIVE_SOURCE._prov
    return info


ROSTERS_CSV = os.path.join(DATA_DIR, "real", "rosters_pilot.csv")


def rosters_info(sample: int = 40) -> dict:
    """The raw NCAA roster data behind the `d1_players` outcome (real source only)."""
    if not ACTIVE_SOURCE.is_real or not os.path.exists(ROSTERS_CSV):
        return {"available": False}
    r = pd.read_csv(ROSTERS_CSV)
    df = get_dataframe()
    by_year = r.groupby("season").size().to_dict()
    return {
        "available": True,
        "description": ("One row per player-season, scraped from public NCAA Division I tennis "
                        "team roster pages. A community's `d1_players` value = the number of "
                        "these rows whose hometown geocodes to that county, that year."),
        "player_seasons": int(len(r)),
        "schools": int(r["school"].nunique()),
        "conferences": sorted(r["conference"].dropna().unique().tolist()),
        "seasons": {int(k): int(v) for k, v in sorted(by_year.items())},
        "by_gender": r["gender"].value_counts(dropna=False).to_dict(),
        "placed_in_a_us_county": int(df["d1_players"].sum()),
        "columns": list(r.columns),
        "sample": r.sample(min(sample, len(r)), random_state=1)
                   .sort_values(["season", "school"]).to_dict(orient="records"),
    }


# legacy attribute-style access (kept for any older imports)
PREDICTORS = predictors()
OUTCOMES = outcomes()
